# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: dist/openapi/definition/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warn
    spec: warn
referenceDocs:
  #htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
