# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: dist/openapi/definition/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warn
    spec: warn
    no-identical-paths: warn
    path-parameters-defined: warn
referenceDocs:
  expandResponses: "200,201"
  theme:
    colors:
      primary:
        main: "#32329f"
